[package]
name = "Virtuoso-l"
version = "0.1.0"
edition = "2021"

[dependencies]
gpio-cdev = { version = "0.4", optional = true }
serial = { version = "0.4.0", optional = true }
slint = { version = "1.12.0", default-features = false, features = ["backend-winit", "renderer-femtovg", "compat-1-2", "std"], optional = true }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
postcard = { version = "1.1.2", features = ["crc", "use-crc", "use-std"] }

[build-dependencies]
zip = "4.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
glob = "0.3.2"

[features]
default = ["console_backend", "slint_frontend", "cyrano_server"]
legacy_backend = ["serial", "gpio-cdev"]
console_backend = []
cyrano_server = []
slint_frontend = ["slint"]
video_recorder = []
gpio_frontend = ["gpio-cdev"]
repeater = ["serial"]

[[bin]]
name = "Virtuoso"
path = "src/main.rs"
