# Virtuoso configuring
## General
export IS_BANANA=True
export INPUT_SUPPORT=False
export CONFIG_FILE=/home/pi/Virtuoso/config.json
export KIVY_FILE=main1920x360_no_video.kv
## Video
export VIDEO_SUPPORT=False
## Logs
export MAIN_LOG_OUT=/dev/null
export MAIN_LOG_ERR=/dev/null
export RECORDER_LOG_OUT=/dev/null
export RECORDER_LOG_ERR=/dev/null
export CUTTER_LOG_OUT=/dev/null
export CUTTER_LOG_ERR=/dev/null
## Updates
export UPDATE_DIR=/home/pi/Virtuoso
## Splash
export SPLASH=Virtuoso_splash1920x360
