FROM ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:latest

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install --assume-yes \
        libsdl2-dev:armhf \
        libsdl2-ttf-dev:armhf
