// Generated file
slint::slint!(export { Virtuoso } from "src/slint/main.slint";);

pub const LAYOUT_1920X550: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        u: 0,
        width: 1920,
        height: 550,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: 0,
        u: 41,
        width: 240,
        height: 539,
        font_size: 550,
    },
    score_l_r: TextProperties {
        x: 240,
        u: 41,
        width: 240,
        height: 540,
        font_size: 550,
    },
    score_r_l: TextProperties {
        x: 1440,
        u: 0,
        width: 254,
        height: 440,
        font_size: 550,
    },
    score_r_r: TextProperties {
        x: 1681,
        u: 41,
        width: 240,
        height: 540,
        font_size: 550,
    },
    epee: TextProperties {
        x: 860,
        u: 429,
        width: 200,
        height: 124,
        font_size: 80,
    },
    sabre: TextProperties {
        x: 1060,
        u: 429,
        width: 200,
        height: 124,
        font_size: 80,
    },
    fleuret: TextProperties {
        x: 660,
        u: 429,
        width: 200,
        height: 124,
        font_size: 80,
    },
    auto_score_status: TextProperties {
        x: 491,
        u: 480,
        width: 120,
        height: 99,
        font_size: 24,
    },
    auto_timer_status: TextProperties {
        x: 1318,
        u: 480,
        width: 120,
        height: 99,
        font_size: 24,
    },
    prioriry_l_cap: TextProperties {
        x: 501,
        u: 325,
        width: 55,
        height: 180,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 526,
        u: 430,
        width: 80,
        height: 55,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1329,
        u: 325,
        width: 45,
        height: 180,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1354,
        u: 430,
        width: 80,
        height: 55,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 496,
        u: 285,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 496,
        u: 285,
        width: 100,
        height: 55,
        font_size: 36,
    },
    penalty_l_rect: RectangleProperties {
        x: 496,
        u: 220,
        width: 100,
        height: 55,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 496,
        u: 220,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 496,
        u: 145,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 496,
        u: 145,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_l_top_rect: RectangleProperties {
        x: 496,
        u: 80,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 496,
        u: 80,
        width: 100,
        height: 55,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1324,
        u: 285,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1324,
        u: 285,
        width: 100,
        height: 55,
        font_size: 36,
    },
    penalty_r_rect: RectangleProperties {
        x: 1324,
        u: 220,
        width: 100,
        height: 55,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1324,
        u: 220,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1324,
        u: 145,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1324,
        u: 145,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1324,
        u: 80,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1324,
        u: 80,
        width: 100,
        height: 55,
        font_size: 36,
    },
    Rectangle: RectangleProperties {
        x: 378,
        u: 37,
        width: 461,
        height: 43,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1243,
        u: 16,
        width: 308,
        height: 63,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 591,
        u: 135,
        width: 745,
        height: 10,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1338,
        u: 200,
        width: 12,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1337,
        u: 275,
        width: 7,
        height: 10,
        radius: 0,
    },
    period: TextProperties {
        x: 604,
        u: 201,
        width: 152,
        height: 212,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 604,
        u: 37,
        width: 76,
        height: 175,
        font_size: 120,
    },
    passive_counter_sec: TextProperties {
        x: 680,
        u: 37,
        width: 76,
        height: 175,
        font_size: 120,
    },
    Rectangle: RectangleProperties {
        x: 579,
        u: 200,
        width: 16,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 620,
        u: 163,
        width: 16,
        height: 19,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 696,
        u: 111,
        width: 16,
        height: 13,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 686,
        u: 234,
        width: 37,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 480,
        u: 124,
        width: 16,
        height: 58,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 764,
        u: 80,
        width: 544,
        height: 365,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 748,
        u: 101,
        width: 16,
        height: 53,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 710,
        u: 445,
        width: 77,
        height: 22,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1308,
        u: 99,
        width: 16,
        height: 64,
        radius: 0,
    },
    timer_m: TextProperties {
        x: 765,
        u: 80,
        width: 160,
        height: 365,
        font_size: 320,
    },
    timer_colon: TextProperties {
        x: 925,
        u: 80,
        width: 63,
        height: 365,
        font_size: 330,
    },
    timer_d: TextProperties {
        x: 988,
        u: 80,
        width: 160,
        height: 365,
        font_size: 330,
    },
    timer_s: TextProperties {
        x: 1148,
        u: 80,
        width: 160,
        height: 365,
        font_size: 330,
    },
    Rectangle: RectangleProperties {
        x: 1424,
        u: 97,
        width: 16,
        height: 24,
        radius: 0,
    },
    passive_indicator: RectangleProperties {
        x: 496,
        u: 10,
        width: 928,
        height: 40,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 27,
        u: 10,
        width: 268,
        height: 40,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1625,
        u: 10,
        width: 282,
        height: 40,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 319,
        u: 10,
        width: 134,
        height: 40,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1467,
        u: 10,
        width: 134,
        height: 40,
        radius: 3,
    },
    Rectangle: RectangleProperties {
        x: 20,
        u: 38,
        width: 7,
        height: 121,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 452,
        u: 8,
        width: 26,
        height: 186,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 80,
        u: 0,
        width: 29,
        height: 30,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1499,
        u: 0,
        width: 140,
        height: 30,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 0,
        u: 19,
        width: 27,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1893,
        u: 13,
        width: 27,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 295,
        u: 20,
        width: 24,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1601,
        u: 24,
        width: 24,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 596,
        u: 34,
        width: 16,
        height: 66,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1424,
        u: 34,
        width: 16,
        height: 66,
        radius: 0,
    },
    recording_indicator: RectangleProperties {
        x: 1256,
        u: 80,
        width: 32,
        height: 32,
        radius: 16,
    },
    LAYOUT_1920X480: TextProperties {
        x: 0,
        u: 0,
        width: 110,
        height: 16,
        font_size: 14,
    },
};

pub const LAYOUT_1920X1080: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        u: 0,
        width: 1920,
        height: 1080,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: 0,
        u: 540,
        width: 240,
        height: 539,
        font_size: 550,
    },
    score_l_r: TextProperties {
        x: 239,
        u: 540,
        width: 240,
        height: 540,
        font_size: 550,
    },
    score_r_l: TextProperties {
        x: 1439,
        u: 483,
        width: 254,
        height: 440,
        font_size: 550,
    },
    score_r_r: TextProperties {
        x: 1680,
        u: 540,
        width: 240,
        height: 540,
        font_size: 550,
    },
    epee: TextProperties {
        x: 859,
        u: 928,
        width: 200,
        height: 125,
        font_size: 80,
    },
    sabre: TextProperties {
        x: 1059,
        u: 928,
        width: 200,
        height: 125,
        font_size: 80,
    },
    fleuret: TextProperties {
        x: 659,
        u: 928,
        width: 200,
        height: 125,
        font_size: 80,
    },
    auto_score_status: TextProperties {
        x: 490,
        u: 979,
        width: 120,
        height: 100,
        font_size: 24,
    },
    auto_timer_status: TextProperties {
        x: 1317,
        u: 979,
        width: 120,
        height: 100,
        font_size: 24,
    },
    prioriry_l_cap: TextProperties {
        x: 500,
        u: 824,
        width: 55,
        height: 180,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 525,
        u: 929,
        width: 80,
        height: 55,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1328,
        u: 824,
        width: 45,
        height: 180,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1353,
        u: 929,
        width: 80,
        height: 55,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 495,
        u: 784,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 495,
        u: 784,
        width: 100,
        height: 55,
        font_size: 36,
    },
    penalty_l_rect: RectangleProperties {
        x: 495,
        u: 719,
        width: 100,
        height: 55,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 495,
        u: 719,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 495,
        u: 644,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 495,
        u: 644,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_l_top_rect: RectangleProperties {
        x: 495,
        u: 579,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 495,
        u: 579,
        width: 100,
        height: 55,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1323,
        u: 784,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1323,
        u: 784,
        width: 100,
        height: 55,
        font_size: 36,
    },
    penalty_r_rect: RectangleProperties {
        x: 1323,
        u: 719,
        width: 100,
        height: 55,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1323,
        u: 719,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1323,
        u: 644,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1323,
        u: 644,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1323,
        u: 579,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1323,
        u: 579,
        width: 100,
        height: 55,
        font_size: 36,
    },
    Rectangle: RectangleProperties {
        x: 377,
        u: 536,
        width: 461,
        height: 43,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1242,
        u: 515,
        width: 308,
        height: 64,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 590,
        u: 634,
        width: 745,
        height: 10,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1337,
        u: 699,
        width: 12,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1336,
        u: 774,
        width: 7,
        height: 10,
        radius: 0,
    },
    period: TextProperties {
        x: 603,
        u: 700,
        width: 152,
        height: 213,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 603,
        u: 537,
        width: 76,
        height: 175,
        font_size: 120,
    },
    passive_counter_sec: TextProperties {
        x: 679,
        u: 537,
        width: 76,
        height: 175,
        font_size: 120,
    },
    Rectangle: RectangleProperties {
        x: 578,
        u: 699,
        width: 16,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 619,
        u: 662,
        width: 16,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 695,
        u: 610,
        width: 16,
        height: 13,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 685,
        u: 733,
        width: 37,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 479,
        u: 623,
        width: 16,
        height: 58,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 763,
        u: 579,
        width: 544,
        height: 365,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 747,
        u: 600,
        width: 16,
        height: 53,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 709,
        u: 944,
        width: 77,
        height: 22,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1307,
        u: 598,
        width: 16,
        height: 64,
        radius: 0,
    },
    timer_m: TextProperties {
        x: 764,
        u: 579,
        width: 160,
        height: 365,
        font_size: 320,
    },
    timer_colon: TextProperties {
        x: 924,
        u: 579,
        width: 63,
        height: 365,
        font_size: 330,
    },
    timer_d: TextProperties {
        x: 987,
        u: 579,
        width: 160,
        height: 365,
        font_size: 330,
    },
    timer_s: TextProperties {
        x: 1147,
        u: 579,
        width: 160,
        height: 365,
        font_size: 330,
    },
    Rectangle: RectangleProperties {
        x: 1423,
        u: 596,
        width: 16,
        height: 24,
        radius: 0,
    },
    passive_indicator: RectangleProperties {
        x: 495,
        u: 509,
        width: 928,
        height: 40,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 26,
        u: 509,
        width: 268,
        height: 40,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1624,
        u: 509,
        width: 282,
        height: 40,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 318,
        u: 509,
        width: 134,
        height: 40,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1466,
        u: 509,
        width: 134,
        height: 40,
        radius: 3,
    },
    Rectangle: RectangleProperties {
        x: 451,
        u: 507,
        width: 26,
        height: 186,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 79,
        u: 1080,
        width: 29,
        height: 30,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1498,
        u: 1080,
        width: 140,
        height: 30,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1892,
        u: 512,
        width: 27,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 294,
        u: 519,
        width: 24,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1600,
        u: 523,
        width: 24,
        height: 20,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 595,
        u: 533,
        width: 16,
        height: 67,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1423,
        u: 533,
        width: 16,
        height: 67,
        radius: 0,
    },
    recording_indicator: RectangleProperties {
        x: 1256,
        u: 580,
        width: 32,
        height: 32,
        radius: 16,
    },
    Rectangle: RectangleProperties {
        x: 0,
        u: 518,
        width: 26,
        height: 17,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 0,
        u: 8,
        width: 26,
        height: 36,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 47,
        u: 0,
        width: 15,
        height: 26,
        radius: 0,
    },
};

pub const LAYOUT_1920X360: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        u: 0,
        width: 1920,
        height: 360,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: 0,
        u: 48,
        width: 180,
        height: 312,
        font_size: 370,
    },
    score_l_r: TextProperties {
        x: 180,
        u: 48,
        width: 180,
        height: 311,
        font_size: 370,
    },
    score_r_l: TextProperties {
        x: 1560,
        u: 47,
        width: 180,
        height: 312,
        font_size: 370,
    },
    score_r_r: TextProperties {
        x: 1740,
        u: 48,
        width: 180,
        height: 312,
        font_size: 370,
    },
    epee: TextProperties {
        x: 927,
        u: 280,
        width: 160,
        height: 80,
        font_size: 60,
    },
    sabre: TextProperties {
        x: 1087,
        u: 280,
        width: 160,
        height: 80,
        font_size: 60,
    },
    fleuret: TextProperties {
        x: 767,
        u: 279,
        width: 160,
        height: 80,
        font_size: 60,
    },
    auto_score_status: TextProperties {
        x: 360,
        u: 280,
        width: 120,
        height: 80,
        font_size: 32,
    },
    auto_timer_status: TextProperties {
        x: 1440,
        u: 280,
        width: 120,
        height: 80,
        font_size: 32,
    },
    prioriry_l_cap: TextProperties {
        x: 365,
        u: 104,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 390,
        u: 188,
        width: 80,
        height: 44,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1445,
        u: 104,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1470,
        u: 188,
        width: 80,
        height: 44,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 492,
        u: 240,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 492,
        u: 240,
        width: 100,
        height: 44,
        font_size: 36,
    },
    penalty_l_rect: RectangleProperties {
        x: 492,
        u: 188,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 492,
        u: 188,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 492,
        u: 128,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 492,
        u: 128,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_l_top_rect: RectangleProperties {
        x: 492,
        u: 76,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 492,
        u: 76,
        width: 100,
        height: 44,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1328,
        u: 240,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1328,
        u: 240,
        width: 100,
        height: 44,
        font_size: 36,
    },
    penalty_r_rect: RectangleProperties {
        x: 1328,
        u: 188,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1328,
        u: 188,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1328,
        u: 128,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1328,
        u: 128,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1328,
        u: 76,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1328,
        u: 76,
        width: 100,
        height: 44,
        font_size: 36,
    },
    period: TextProperties {
        x: 604,
        u: 190,
        width: 152,
        height: 170,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 604,
        u: 48,
        width: 76,
        height: 140,
        font_size: 160,
    },
    passive_counter_sec: TextProperties {
        x: 680,
        u: 48,
        width: 76,
        height: 140,
        font_size: 160,
    },
    timer_m: TextProperties {
        x: 784,
        u: 24,
        width: 140,
        height: 270,
        font_size: 280,
    },
    timer_colon: TextProperties {
        x: 925,
        u: 24,
        width: 50,
        height: 270,
        font_size: 280,
    },
    timer_d: TextProperties {
        x: 975,
        u: 24,
        width: 140,
        height: 270,
        font_size: 280,
    },
    timer_s: TextProperties {
        x: 1115,
        u: 24,
        width: 140,
        height: 270,
        font_size: 280,
    },
    passive_indicator: RectangleProperties {
        x: 491,
        u: 8,
        width: 936,
        height: 32,
        radius: 0,
    },
    left_color_indicator: RectangleProperties {
        x: 8,
        u: 8,
        width: 224,
        height: 32,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1688,
        u: 8,
        width: 224,
        height: 32,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 240,
        u: 8,
        width: 120,
        height: 32,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1568,
        u: 8,
        width: 112,
        height: 32,
        radius: 3,
    },
    recording_indicator: RectangleProperties {
        x: 1254,
        u: 56,
        width: 32,
        height: 32,
        radius: 16,
    },
};

pub const LAYOUT_1920X480: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        u: 0,
        width: 1920,
        height: 480,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: 0,
        u: 48,
        width: 240,
        height: 431,
        font_size: 500,
    },
    score_l_r: TextProperties {
        x: 240,
        u: 48,
        width: 240,
        height: 432,
        font_size: 500,
    },
    score_r_l: TextProperties {
        x: 1440,
        u: 47,
        width: 240,
        height: 432,
        font_size: 500,
    },
    score_r_r: TextProperties {
        x: 1680,
        u: 47,
        width: 240,
        height: 432,
        font_size: 500,
    },
    epee: TextProperties {
        x: 860,
        u: 380,
        width: 200,
        height: 100,
        font_size: 80,
    },
    sabre: TextProperties {
        x: 1060,
        u: 380,
        width: 200,
        height: 100,
        font_size: 80,
    },
    fleuret: TextProperties {
        x: 660,
        u: 379,
        width: 200,
        height: 100,
        font_size: 80,
    },
    auto_score_status: TextProperties {
        x: 486,
        u: 400,
        width: 120,
        height: 80,
        font_size: 32,
    },
    auto_timer_status: TextProperties {
        x: 1314,
        u: 400,
        width: 120,
        height: 80,
        font_size: 32,
    },
    prioriry_l_cap: TextProperties {
        x: 501,
        u: 276,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 526,
        u: 360,
        width: 80,
        height: 44,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1329,
        u: 276,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1354,
        u: 360,
        width: 80,
        height: 44,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 496,
        u: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 496,
        u: 244,
        width: 100,
        height: 44,
        font_size: 36,
    },
    penalty_l_rect: RectangleProperties {
        x: 496,
        u: 192,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 496,
        u: 192,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 496,
        u: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 496,
        u: 132,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_l_top_rect: RectangleProperties {
        x: 496,
        u: 80,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 496,
        u: 80,
        width: 100,
        height: 44,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1324,
        u: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1324,
        u: 244,
        width: 100,
        height: 44,
        font_size: 36,
    },
    penalty_r_rect: RectangleProperties {
        x: 1324,
        u: 192,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1324,
        u: 192,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1324,
        u: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1324,
        u: 132,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1324,
        u: 80,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1324,
        u: 80,
        width: 100,
        height: 44,
        font_size: 36,
    },
    Rectangle: RectangleProperties {
        x: 378,
        u: 46,
        width: 461,
        height: 34,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1243,
        u: 29,
        width: 308,
        height: 51,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 591,
        u: 124,
        width: 744,
        height: 8,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1338,
        u: 176,
        width: 12,
        height: 16,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1337,
        u: 236,
        width: 7,
        height: 8,
        radius: 0,
    },
    period: TextProperties {
        x: 604,
        u: 206,
        width: 152,
        height: 170,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 604,
        u: 69,
        width: 76,
        height: 140,
        font_size: 160,
    },
    passive_counter_sec: TextProperties {
        x: 680,
        u: 69,
        width: 76,
        height: 140,
        font_size: 160,
    },
    Rectangle: RectangleProperties {
        x: 579,
        u: 176,
        width: 16,
        height: 16,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 620,
        u: 146,
        width: 16,
        height: 16,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 696,
        u: 105,
        width: 15,
        height: 10,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 686,
        u: 203,
        width: 37,
        height: 16,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 480,
        u: 115,
        width: 16,
        height: 47,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 764,
        u: 80,
        width: 544,
        height: 292,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 748,
        u: 97,
        width: 16,
        height: 42,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 710,
        u: 372,
        width: 77,
        height: 18,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1308,
        u: 95,
        width: 16,
        height: 51,
        radius: 0,
    },
    timer_m: TextProperties {
        x: 764,
        u: 80,
        width: 160,
        height: 292,
        font_size: 320,
    },
    timer_colon: TextProperties {
        x: 925,
        u: 80,
        width: 63,
        height: 292,
        font_size: 330,
    },
    timer_d: TextProperties {
        x: 988,
        u: 80,
        width: 160,
        height: 292,
        font_size: 330,
    },
    timer_s: TextProperties {
        x: 1148,
        u: 80,
        width: 160,
        height: 292,
        font_size: 330,
    },
    Rectangle: RectangleProperties {
        x: 1424,
        u: 93,
        width: 16,
        height: 19,
        radius: 0,
    },
    passive_indicator: RectangleProperties {
        x: 496,
        u: 24,
        width: 928,
        height: 32,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 27,
        u: 24,
        width: 268,
        height: 32,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1625,
        u: 24,
        width: 268,
        height: 32,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 319,
        u: 24,
        width: 134,
        height: 32,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1467,
        u: 24,
        width: 134,
        height: 32,
        radius: 3,
    },
    Rectangle: RectangleProperties {
        x: 20,
        u: 47,
        width: 7,
        height: 97,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 452,
        u: 22,
        width: 26,
        height: 149,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 80,
        u: 0,
        width: 29,
        height: 24,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1499,
        u: 0,
        width: 139,
        height: 24,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 0,
        u: 30,
        width: 27,
        height: 16,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1893,
        u: 25,
        width: 27,
        height: 16,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 295,
        u: 32,
        width: 24,
        height: 16,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1601,
        u: 35,
        width: 24,
        height: 16,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 596,
        u: 43,
        width: 16,
        height: 54,
        radius: 0,
    },
    Rectangle: RectangleProperties {
        x: 1424,
        u: 43,
        width: 16,
        height: 54,
        radius: 0,
    },
    recording_indicator: RectangleProperties {
        x: 1258,
        u: 64,
        width: 32,
        height: 32,
        radius: 16,
    },
    cyrano_status: TextProperties {
        x: 915,
        u: 74,
        width: 86,
        height: 39,
        font_size: 32,
    },
};

pub const LAYOUT_480X320: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        u: 0,
        width: 480,
        height: 320,
        radius: 0,
    },
    fleuret: TextProperties {
        x: 90,
        u: 250,
        width: 100,
        height: 70,
        font_size: 40,
    },
    epee: TextProperties {
        x: 190,
        u: 250,
        width: 100,
        height: 70,
        font_size: 40,
    },
    sabre: TextProperties {
        x: 290,
        u: 250,
        width: 100,
        height: 70,
        font_size: 40,
    },
    prioriry_l_cap: TextProperties {
        x: 0,
        u: 247,
        width: 37,
        height: 68,
        font_size: 80,
    },
    priority_l_text: TextProperties {
        x: 13,
        u: 287,
        width: 70,
        height: 29,
        font_size: 30,
    },
    prioriry_r_cap: TextProperties {
        x: 396,
        u: 246,
        width: 37,
        height: 68,
        font_size: 80,
    },
    priority_r_text: TextProperties {
        x: 409,
        u: 286,
        width: 71,
        height: 29,
        font_size: 30,
    },
    timer_m: TextProperties {
        x: 0,
        u: 2,
        width: 140,
        height: 250,
        font_size: 300,
    },
    timer_colon: TextProperties {
        x: 140,
        u: 0,
        width: 60,
        height: 250,
        font_size: 300,
    },
    timer_d: TextProperties {
        x: 200,
        u: 0,
        width: 140,
        height: 250,
        font_size: 300,
    },
    timer_s: TextProperties {
        x: 339,
        u: 0,
        width: 140,
        height: 250,
        font_size: 300,
    },
};
