
pub struct RectangleProperties {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
    pub radius: f32,
}

pub struct TextProperties {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
    pub font_size: f32,
}

pub struct Layout {
    pub background: RectangleProperties,
    pub left_nation: TextProperties,
    pub left_flag: RectangleProperties,
    pub left_name: TextProperties,
    pub right_nation: TextProperties,
    pub right_flag: RectangleProperties,
    pub right_name: TextProperties,
    pub score_l_l: TextProperties,
    pub score_l_r: TextProperties,
    pub score_r_l: TextProperties,
    pub score_r_r: TextProperties,
    pub epee: TextProperties,
    pub sabre: TextProperties,
    pub fleuret: TextProperties,
    pub auto_score_status: TextProperties,
    pub auto_timer_status: TextProperties,
    pub priority_l_cap: TextProperties,
    pub priority_l_text: TextProperties,
    pub priority_r_cap: TextProperties,
    pub priority_r_text: TextProperties,
    pub caution_l_rect: RectangleProperties,
    pub caution_l_text: TextProperties,
    pub penalty_l_rect: RectangleProperties,
    pub penalty_l_text: TextProperties,
    pub passive_l_bot_rect: RectangleProperties,
    pub passive_l_bot_text: TextProperties,
    pub passive_l_top_rect: RectangleProperties,
    pub passive_l_top_text: TextProperties,
    pub caution_r_rect: RectangleProperties,
    pub caution_r_text: TextProperties,
    pub penalty_r_rect: RectangleProperties,
    pub penalty_r_text: TextProperties,
    pub passive_r_bot_rect: RectangleProperties,
    pub passive_r_bot_text: TextProperties,
    pub passive_r_top_rect: RectangleProperties,
    pub passive_r_top_text: TextProperties,
    pub period: TextProperties,
    pub passive_counter_dec: TextProperties,
    pub passive_counter_sec: TextProperties,
    pub timer_m: TextProperties,
    pub timer_colon: TextProperties,
    pub timer_d: TextProperties,
    pub timer_s: TextProperties,
    pub passive_indicator: RectangleProperties,
    pub left_color_indicator: RectangleProperties,
    pub right_color_indicator: RectangleProperties,
    pub left_white_indicator: RectangleProperties,
    pub right_white_indicator: RectangleProperties,
    pub recording_indicator: RectangleProperties,
    pub timer_text: TextProperties,
}
