// Genetated file
slint::slint!(export { Virtuoso } from "src/slint/main.slint";);

pub const LAYOUT_1920X480: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 480,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: -100,
        y: -52,
        width: 440,
        height: 632,
        font_size: 499,
    },
    score_l_r: TextProperties {
        x: 140,
        y: -52,
        width: 440,
        height: 632,
        font_size: 499,
    },
    score_r_l: TextProperties {
        x: 1340,
        y: -52,
        width: 440,
        height: 632,
        font_size: 499,
    },
    score_r_r: TextProperties {
        x: 1581,
        y: -52,
        width: 440,
        height: 632,
        font_size: 499,
    },
    epee: TextProperties {
        x: 760,
        y: 280,
        width: 400,
        height: 300,
        font_size: 79,
    },
    sabre: TextProperties {
        x: 960,
        y: 280,
        width: 400,
        height: 300,
        font_size: 79,
    },
    fleuret: TextProperties {
        x: 560,
        y: 280,
        width: 400,
        height: 300,
        font_size: 79,
    },
    auto_score_status: TextProperties {
        x: 386,
        y: 300,
        width: 320,
        height: 280,
        font_size: 31,
    },
    auto_timer_status: TextProperties {
        x: 1214,
        y: 300,
        width: 320,
        height: 280,
        font_size: 31,
    },
    prioriry_l_cap: TextProperties {
        x: 401,
        y: 176,
        width: 255,
        height: 344,
        font_size: 119,
    },
    priority_l_text: TextProperties {
        x: 426,
        y: 260,
        width: 280,
        height: 244,
        font_size: 35,
    },
    priority_r_cap: TextProperties {
        x: 1229,
        y: 176,
        width: 255,
        height: 344,
        font_size: 119,
    },
    priority_r_text: TextProperties {
        x: 1254,
        y: 260,
        width: 280,
        height: 244,
        font_size: 35,
    },
    caution_l_rect: RectangleProperties {
        x: 496,
        y: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 396,
        y: 144,
        width: 300,
        height: 244,
        font_size: 35,
    },
    penalty_l_rect: RectangleProperties {
        x: 496,
        y: 192,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 396,
        y: 92,
        width: 300,
        height: 244,
        font_size: 35,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 496,
        y: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 396,
        y: 32,
        width: 300,
        height: 244,
        font_size: 35,
    },
    passive_l_top_rect: RectangleProperties {
        x: 496,
        y: 80,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 396,
        y: -20,
        width: 300,
        height: 244,
        font_size: 35,
    },
    caution_r_rect: RectangleProperties {
        x: 1324,
        y: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1224,
        y: 144,
        width: 300,
        height: 244,
        font_size: 35,
    },
    penalty_r_rect: RectangleProperties {
        x: 1324,
        y: 192,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1224,
        y: 92,
        width: 300,
        height: 244,
        font_size: 35,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1324,
        y: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1224,
        y: 32,
        width: 300,
        height: 244,
        font_size: 35,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1324,
        y: 80,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1224,
        y: -20,
        width: 300,
        height: 244,
        font_size: 35,
    },
    period: TextProperties {
        x: 504,
        y: 107,
        width: 352,
        height: 371,
        font_size: 199,
    },
    passive_counter_dec: TextProperties {
        x: 504,
        y: -31,
        width: 276,
        height: 340,
        font_size: 159,
    },
    passive_counter_sec: TextProperties {
        x: 580,
        y: -31,
        width: 276,
        height: 340,
        font_size: 159,
    },
    timer_m: TextProperties {
        x: 665,
        y: -20,
        width: 360,
        height: 492,
        font_size: 319,
    },
    timer_colon: TextProperties {
        x: 825,
        y: -20,
        width: 263,
        height: 492,
        font_size: 329,
    },
    timer_d: TextProperties {
        x: 888,
        y: -20,
        width: 360,
        height: 492,
        font_size: 329,
    },
    timer_s: TextProperties {
        x: 1048,
        y: -20,
        width: 360,
        height: 492,
        font_size: 329,
    },
    passive_indicator: RectangleProperties {
        x: 496,
        y: 24,
        width: 928,
        height: 32,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 27,
        y: 24,
        width: 268,
        height: 32,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1625,
        y: 24,
        width: 268,
        height: 32,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 319,
        y: 24,
        width: 134,
        height: 32,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1467,
        y: 24,
        width: 134,
        height: 32,
        radius: 3,
    },
    recording_indicator: RectangleProperties {
        x: 1258,
        y: 64,
        width: 32,
        height: 32,
        radius: 16,
    },
};
