// Generated file
slint::slint!(export { Virtuoso } from "src/slint/main.slint";);

pub const LAYOUT_1920X550: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 550,
        radius: 0,
    },
    left_nation: TextProperties {
        x: -74,
        y: -394,
        width: 284,
        height: 271,
        font_size: 60 + 1,
    },
    left_flag: RectangleProperties {
        x: 118,
        y: -281,
        width: 72,
        height: 47,
        radius: 0,
    },
    left_name: TextProperties {
        x: -100,
        y: -322,
        width: 680,
        height: 308,
        font_size: 90 + 1,
    },
    right_nation: TextProperties {
        x: 1366,
        y: -394,
        width: 284,
        height: 271,
        font_size: 60 + 1,
    },
    right_flag: RectangleProperties {
        x: 1558,
        y: -281,
        width: 72,
        height: 47,
        radius: 0,
    },
    right_name: TextProperties {
        x: 1340,
        y: -322,
        width: 680,
        height: 308,
        font_size: 90 + 1,
    },
    score_l_l: TextProperties {
        x: -100,
        y: -59,
        width: 440,
        height: 739,
        font_size: 550 + 1,
    },
    score_l_r: TextProperties {
        x: 140,
        y: -59,
        width: 440,
        height: 740,
        font_size: 550 + 1,
    },
    score_r_l: TextProperties {
        x: 1340,
        y: -116,
        width: 454,
        height: 640,
        font_size: 550 + 1,
    },
    score_r_r: TextProperties {
        x: 1581,
        y: -59,
        width: 440,
        height: 740,
        font_size: 550 + 1,
    },
    epee: TextProperties {
        x: 760,
        y: 329,
        width: 400,
        height: 324,
        font_size: 80 + 1,
    },
    sabre: TextProperties {
        x: 960,
        y: 329,
        width: 400,
        height: 324,
        font_size: 80 + 1,
    },
    fleuret: TextProperties {
        x: 560,
        y: 329,
        width: 400,
        height: 324,
        font_size: 80 + 1,
    },
    auto_score_status: TextProperties {
        x: 391,
        y: 380,
        width: 320,
        height: 299,
        font_size: 24 + 1,
    },
    auto_timer_status: TextProperties {
        x: 1218,
        y: 380,
        width: 320,
        height: 299,
        font_size: 24 + 1,
    },
    priority_l_cap: TextProperties {
        x: 401,
        y: 225,
        width: 255,
        height: 380,
        font_size: 120 + 1,
    },
    priority_l_text: TextProperties {
        x: 426,
        y: 330,
        width: 280,
        height: 255,
        font_size: 36 + 1,
    },
    priority_r_cap: TextProperties {
        x: 1229,
        y: 225,
        width: 245,
        height: 380,
        font_size: 120 + 1,
    },
    priority_r_text: TextProperties {
        x: 1254,
        y: 330,
        width: 280,
        height: 255,
        font_size: 36 + 1,
    },
    caution_l_rect: RectangleProperties {
        x: 496,
        y: 285,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 396,
        y: 185,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    penalty_l_rect: RectangleProperties {
        x: 496,
        y: 220,
        width: 100,
        height: 55,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 396,
        y: 120,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 496,
        y: 145,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 396,
        y: 45,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    passive_l_top_rect: RectangleProperties {
        x: 496,
        y: 80,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 396,
        y: -20,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    caution_r_rect: RectangleProperties {
        x: 1324,
        y: 285,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1224,
        y: 185,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    penalty_r_rect: RectangleProperties {
        x: 1324,
        y: 220,
        width: 100,
        height: 55,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1224,
        y: 120,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1324,
        y: 145,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1224,
        y: 45,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1324,
        y: 80,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1224,
        y: -20,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    period: TextProperties {
        x: 504,
        y: 101,
        width: 352,
        height: 412,
        font_size: 200 + 1,
    },
    passive_counter_dec: TextProperties {
        x: 504,
        y: -63,
        width: 276,
        height: 375,
        font_size: 120 + 1,
    },
    passive_counter_sec: TextProperties {
        x: 580,
        y: -63,
        width: 276,
        height: 375,
        font_size: 120 + 1,
    },
    timer_m: TextProperties {
        x: 665,
        y: -20,
        width: 360,
        height: 565,
        font_size: 320 + 1,
    },
    timer_colon: TextProperties {
        x: 825,
        y: -20,
        width: 263,
        height: 565,
        font_size: 330 + 1,
    },
    timer_d: TextProperties {
        x: 888,
        y: -20,
        width: 360,
        height: 565,
        font_size: 330 + 1,
    },
    timer_s: TextProperties {
        x: 1048,
        y: -20,
        width: 360,
        height: 565,
        font_size: 330 + 1,
    },
    passive_indicator: RectangleProperties {
        x: 496,
        y: 10,
        width: 928,
        height: 40,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 27,
        y: 10,
        width: 268,
        height: 40,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1625,
        y: 10,
        width: 282,
        height: 40,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 319,
        y: 10,
        width: 134,
        height: 40,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1467,
        y: 10,
        width: 134,
        height: 40,
        radius: 3,
    },
    recording_indicator: RectangleProperties {
        x: 1256,
        y: 80,
        width: 32,
        height: 32,
        radius: 16,
    },
    timer_text: TextProperties {
        x: 665,
        y: -19,
        width: 743,
        height: 565,
        font_size: 64 + 1,
    },
};

pub const LAYOUT_1920X1080: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 1080,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: -100,
        y: 440,
        width: 440,
        height: 739,
        font_size: 550 + 1,
    },
    score_l_r: TextProperties {
        x: 139,
        y: 440,
        width: 440,
        height: 740,
        font_size: 550 + 1,
    },
    score_r_l: TextProperties {
        x: 1339,
        y: 383,
        width: 454,
        height: 640,
        font_size: 550 + 1,
    },
    score_r_r: TextProperties {
        x: 1580,
        y: 440,
        width: 440,
        height: 740,
        font_size: 550 + 1,
    },
    epee: TextProperties {
        x: 759,
        y: 828,
        width: 400,
        height: 325,
        font_size: 80 + 1,
    },
    sabre: TextProperties {
        x: 959,
        y: 828,
        width: 400,
        height: 325,
        font_size: 80 + 1,
    },
    fleuret: TextProperties {
        x: 559,
        y: 828,
        width: 400,
        height: 325,
        font_size: 80 + 1,
    },
    auto_score_status: TextProperties {
        x: 390,
        y: 879,
        width: 320,
        height: 300,
        font_size: 24 + 1,
    },
    auto_timer_status: TextProperties {
        x: 1217,
        y: 879,
        width: 320,
        height: 300,
        font_size: 24 + 1,
    },
    priority_l_cap: TextProperties {
        x: 400,
        y: 724,
        width: 255,
        height: 380,
        font_size: 120 + 1,
    },
    priority_l_text: TextProperties {
        x: 425,
        y: 829,
        width: 280,
        height: 255,
        font_size: 36 + 1,
    },
    priority_r_cap: TextProperties {
        x: 1228,
        y: 724,
        width: 245,
        height: 380,
        font_size: 120 + 1,
    },
    priority_r_text: TextProperties {
        x: 1253,
        y: 829,
        width: 280,
        height: 255,
        font_size: 36 + 1,
    },
    caution_l_rect: RectangleProperties {
        x: 495,
        y: 784,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 395,
        y: 684,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    penalty_l_rect: RectangleProperties {
        x: 495,
        y: 719,
        width: 100,
        height: 55,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 395,
        y: 619,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 495,
        y: 644,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 395,
        y: 544,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    passive_l_top_rect: RectangleProperties {
        x: 495,
        y: 579,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 395,
        y: 479,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    caution_r_rect: RectangleProperties {
        x: 1323,
        y: 784,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1223,
        y: 684,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    penalty_r_rect: RectangleProperties {
        x: 1323,
        y: 719,
        width: 100,
        height: 55,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1223,
        y: 619,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1323,
        y: 644,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1223,
        y: 544,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1323,
        y: 579,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1223,
        y: 479,
        width: 300,
        height: 255,
        font_size: 36 + 1,
    },
    period: TextProperties {
        x: 503,
        y: 600,
        width: 352,
        height: 413,
        font_size: 200 + 1,
    },
    passive_counter_dec: TextProperties {
        x: 503,
        y: 437,
        width: 276,
        height: 375,
        font_size: 120 + 1,
    },
    passive_counter_sec: TextProperties {
        x: 579,
        y: 437,
        width: 276,
        height: 375,
        font_size: 120 + 1,
    },
    timer_m: TextProperties {
        x: 664,
        y: 479,
        width: 360,
        height: 565,
        font_size: 320 + 1,
    },
    timer_colon: TextProperties {
        x: 824,
        y: 479,
        width: 263,
        height: 565,
        font_size: 330 + 1,
    },
    timer_d: TextProperties {
        x: 887,
        y: 479,
        width: 360,
        height: 565,
        font_size: 330 + 1,
    },
    timer_s: TextProperties {
        x: 1047,
        y: 479,
        width: 360,
        height: 565,
        font_size: 330 + 1,
    },
    passive_indicator: RectangleProperties {
        x: 495,
        y: 509,
        width: 928,
        height: 40,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 26,
        y: 509,
        width: 268,
        height: 40,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1624,
        y: 509,
        width: 282,
        height: 40,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 318,
        y: 509,
        width: 134,
        height: 40,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1466,
        y: 509,
        width: 134,
        height: 40,
        radius: 3,
    },
    recording_indicator: RectangleProperties {
        x: 1256,
        y: 580,
        width: 32,
        height: 32,
        radius: 16,
    },
    left_nation: TextProperties {
        x: -74,
        y: -74,
        width: 284,
        height: 272,
        font_size: 60 + 1,
    },
    left_flag: RectangleProperties {
        x: 118,
        y: 39,
        width: 72,
        height: 48,
        radius: 0,
    },
    left_name: TextProperties {
        x: -100,
        y: -2,
        width: 680,
        height: 308,
        font_size: 90 + 1,
    },
    right_nation: TextProperties {
        x: 1366,
        y: -74,
        width: 284,
        height: 272,
        font_size: 60 + 1,
    },
    right_flag: RectangleProperties {
        x: 1558,
        y: 39,
        width: 72,
        height: 48,
        radius: 0,
    },
    right_name: TextProperties {
        x: 1340,
        y: -2,
        width: 680,
        height: 308,
        font_size: 90 + 1,
    },
    timer_text: TextProperties {
        x: 665,
        y: 479,
        width: 743,
        height: 565,
        font_size: 64 + 1,
    },
};

pub const LAYOUT_1920X360: Layout = Layout {
    left_nation: TextProperties {
        x: -74,
        y: -394,
        width: 284,
        height: 272,
        font_size: 60 + 1,
    },
    left_flag: RectangleProperties {
        x: 118,
        y: -281,
        width: 72,
        height: 48,
        radius: 0,
    },
    left_name: TextProperties {
        x: -100,
        y: -322,
        width: 680,
        height: 308,
        font_size: 90 + 1,
    },
    right_nation: TextProperties {
        x: 1366,
        y: -394,
        width: 284,
        height: 272,
        font_size: 60 + 1,
    },
    right_flag: RectangleProperties {
        x: 1558,
        y: -281,
        width: 72,
        height: 48,
        radius: 0,
    },
    right_name: TextProperties {
        x: 1340,
        y: -322,
        width: 680,
        height: 308,
        font_size: 90 + 1,
    },
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 360,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: -100,
        y: -52,
        width: 380,
        height: 512,
        font_size: 370 + 1,
    },
    score_l_r: TextProperties {
        x: 80,
        y: -52,
        width: 380,
        height: 511,
        font_size: 370 + 1,
    },
    score_r_l: TextProperties {
        x: 1460,
        y: -53,
        width: 380,
        height: 512,
        font_size: 370 + 1,
    },
    score_r_r: TextProperties {
        x: 1640,
        y: -52,
        width: 380,
        height: 512,
        font_size: 370 + 1,
    },
    epee: TextProperties {
        x: 827,
        y: 180,
        width: 360,
        height: 280,
        font_size: 60 + 1,
    },
    sabre: TextProperties {
        x: 987,
        y: 180,
        width: 360,
        height: 280,
        font_size: 60 + 1,
    },
    fleuret: TextProperties {
        x: 667,
        y: 179,
        width: 360,
        height: 280,
        font_size: 60 + 1,
    },
    auto_score_status: TextProperties {
        x: 260,
        y: 180,
        width: 320,
        height: 280,
        font_size: 32 + 1,
    },
    auto_timer_status: TextProperties {
        x: 1340,
        y: 180,
        width: 320,
        height: 280,
        font_size: 32 + 1,
    },
    priority_l_cap: TextProperties {
        x: 265,
        y: 4,
        width: 255,
        height: 344,
        font_size: 120 + 1,
    },
    priority_l_text: TextProperties {
        x: 290,
        y: 88,
        width: 280,
        height: 244,
        font_size: 36 + 1,
    },
    priority_r_cap: TextProperties {
        x: 1345,
        y: 4,
        width: 255,
        height: 344,
        font_size: 120 + 1,
    },
    priority_r_text: TextProperties {
        x: 1370,
        y: 88,
        width: 280,
        height: 244,
        font_size: 36 + 1,
    },
    caution_l_rect: RectangleProperties {
        x: 492,
        y: 240,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 392,
        y: 140,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    penalty_l_rect: RectangleProperties {
        x: 492,
        y: 188,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 392,
        y: 88,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 492,
        y: 128,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 392,
        y: 28,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    passive_l_top_rect: RectangleProperties {
        x: 492,
        y: 76,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 392,
        y: -24,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    caution_r_rect: RectangleProperties {
        x: 1328,
        y: 240,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1228,
        y: 140,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    penalty_r_rect: RectangleProperties {
        x: 1328,
        y: 188,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1228,
        y: 88,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1328,
        y: 128,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1228,
        y: 28,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1328,
        y: 76,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1228,
        y: -24,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    period: TextProperties {
        x: 504,
        y: 90,
        width: 352,
        height: 370,
        font_size: 200 + 1,
    },
    passive_counter_dec: TextProperties {
        x: 504,
        y: -52,
        width: 276,
        height: 340,
        font_size: 160 + 1,
    },
    passive_counter_sec: TextProperties {
        x: 580,
        y: -52,
        width: 276,
        height: 340,
        font_size: 160 + 1,
    },
    timer_m: TextProperties {
        x: 684,
        y: -76,
        width: 340,
        height: 470,
        font_size: 280 + 1,
    },
    timer_colon: TextProperties {
        x: 825,
        y: -76,
        width: 250,
        height: 470,
        font_size: 280 + 1,
    },
    timer_d: TextProperties {
        x: 875,
        y: -76,
        width: 340,
        height: 470,
        font_size: 280 + 1,
    },
    timer_s: TextProperties {
        x: 1015,
        y: -76,
        width: 340,
        height: 470,
        font_size: 280 + 1,
    },
    passive_indicator: RectangleProperties {
        x: 491,
        y: 8,
        width: 936,
        height: 32,
        radius: 0,
    },
    left_color_indicator: RectangleProperties {
        x: 8,
        y: 8,
        width: 224,
        height: 32,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1688,
        y: 8,
        width: 224,
        height: 32,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 240,
        y: 8,
        width: 120,
        height: 32,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1568,
        y: 8,
        width: 112,
        height: 32,
        radius: 3,
    },
    recording_indicator: RectangleProperties {
        x: 1254,
        y: 56,
        width: 32,
        height: 32,
        radius: 16,
    },
    timer_text: TextProperties {
        x: 685,
        y: -76,
        width: 662,
        height: 470,
        font_size: 64 + 1,
    },
};

pub const LAYOUT_1920X480: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 480,
        radius: 0,
    },
    left_nation: TextProperties {
        x: -74,
        y: -394,
        width: 284,
        height: 272,
        font_size: 60 + 1,
    },
    left_flag: RectangleProperties {
        x: 118,
        y: -281,
        width: 72,
        height: 48,
        radius: 0,
    },
    left_name: TextProperties {
        x: -100,
        y: -322,
        width: 680,
        height: 308,
        font_size: 90 + 1,
    },
    right_nation: TextProperties {
        x: 1366,
        y: -394,
        width: 284,
        height: 272,
        font_size: 60 + 1,
    },
    right_flag: RectangleProperties {
        x: 1558,
        y: -281,
        width: 72,
        height: 48,
        radius: 0,
    },
    right_name: TextProperties {
        x: 1340,
        y: -322,
        width: 680,
        height: 308,
        font_size: 90 + 1,
    },
    score_l_l: TextProperties {
        x: -100,
        y: -52,
        width: 440,
        height: 631,
        font_size: 500 + 1,
    },
    score_l_r: TextProperties {
        x: 140,
        y: -52,
        width: 440,
        height: 632,
        font_size: 500 + 1,
    },
    score_r_l: TextProperties {
        x: 1340,
        y: -53,
        width: 440,
        height: 632,
        font_size: 500 + 1,
    },
    score_r_r: TextProperties {
        x: 1580,
        y: -53,
        width: 440,
        height: 632,
        font_size: 500 + 1,
    },
    epee: TextProperties {
        x: 760,
        y: 280,
        width: 400,
        height: 300,
        font_size: 80 + 1,
    },
    sabre: TextProperties {
        x: 960,
        y: 280,
        width: 400,
        height: 300,
        font_size: 80 + 1,
    },
    fleuret: TextProperties {
        x: 560,
        y: 279,
        width: 400,
        height: 300,
        font_size: 80 + 1,
    },
    auto_score_status: TextProperties {
        x: 386,
        y: 300,
        width: 320,
        height: 280,
        font_size: 32 + 1,
    },
    auto_timer_status: TextProperties {
        x: 1214,
        y: 300,
        width: 320,
        height: 280,
        font_size: 32 + 1,
    },
    priority_l_cap: TextProperties {
        x: 401,
        y: 176,
        width: 255,
        height: 344,
        font_size: 120 + 1,
    },
    priority_l_text: TextProperties {
        x: 426,
        y: 260,
        width: 280,
        height: 244,
        font_size: 36 + 1,
    },
    priority_r_cap: TextProperties {
        x: 1229,
        y: 176,
        width: 255,
        height: 344,
        font_size: 120 + 1,
    },
    priority_r_text: TextProperties {
        x: 1254,
        y: 260,
        width: 280,
        height: 244,
        font_size: 36 + 1,
    },
    caution_l_rect: RectangleProperties {
        x: 496,
        y: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 396,
        y: 144,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    penalty_l_rect: RectangleProperties {
        x: 496,
        y: 192,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 396,
        y: 92,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 496,
        y: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 396,
        y: 32,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    passive_l_top_rect: RectangleProperties {
        x: 496,
        y: 80,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 396,
        y: -20,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    caution_r_rect: RectangleProperties {
        x: 1324,
        y: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1224,
        y: 144,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    penalty_r_rect: RectangleProperties {
        x: 1324,
        y: 192,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1224,
        y: 92,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1324,
        y: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1224,
        y: 32,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1324,
        y: 80,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1224,
        y: -20,
        width: 300,
        height: 244,
        font_size: 36 + 1,
    },
    period: TextProperties {
        x: 504,
        y: 106,
        width: 352,
        height: 370,
        font_size: 200 + 1,
    },
    passive_counter_dec: TextProperties {
        x: 504,
        y: -31,
        width: 276,
        height: 340,
        font_size: 160 + 1,
    },
    passive_counter_sec: TextProperties {
        x: 580,
        y: -31,
        width: 276,
        height: 340,
        font_size: 160 + 1,
    },
    timer_m: TextProperties {
        x: 664,
        y: -20,
        width: 360,
        height: 492,
        font_size: 320 + 1,
    },
    timer_colon: TextProperties {
        x: 825,
        y: -20,
        width: 263,
        height: 492,
        font_size: 330 + 1,
    },
    timer_d: TextProperties {
        x: 888,
        y: -20,
        width: 360,
        height: 492,
        font_size: 330 + 1,
    },
    timer_s: TextProperties {
        x: 1048,
        y: -20,
        width: 360,
        height: 492,
        font_size: 330 + 1,
    },
    passive_indicator: RectangleProperties {
        x: 496,
        y: 24,
        width: 928,
        height: 32,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 27,
        y: 24,
        width: 268,
        height: 32,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1625,
        y: 24,
        width: 268,
        height: 32,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 319,
        y: 24,
        width: 134,
        height: 32,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1467,
        y: 24,
        width: 134,
        height: 32,
        radius: 3,
    },
    recording_indicator: RectangleProperties {
        x: 1258,
        y: 64,
        width: 32,
        height: 32,
        radius: 16,
    },
    timer_text: TextProperties {
        x: 664,
        y: -20,
        width: 744,
        height: 492,
        font_size: 64 + 1,
    },
};
