#![allow(dead_code)]

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct RectangleProperties {
    pub x: i32,
    pub y: i32,
    pub width: u32,
    pub height: u32,
    pub radius: u32,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TextProperties {
    pub x: i32,
    pub y: i32,
    pub width: u32,
    pub height: u32,
    pub font_size: u16,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CyranoLayout {
    pub left_name: TextProperties,
    pub left_nation: TextProperties,
    pub left_flag: RectangleProperties,
    pub left_score: TextProperties,
    pub left_status: TextProperties,
    pub left_video: TextProperties,
    pub left_medical: TextProperties,
    pub left_reserve: TextProperties,
    pub left_id: TextProperties,
    pub left_photo: RectangleProperties,

    pub right_name: TextProperties,
    pub right_nation: TextProperties,
    pub right_flag: RectangleProperties,
    pub right_score: TextProperties,
    pub right_status: TextProperties,
    pub right_video: TextProperties,
    pub right_medical: TextProperties,
    pub right_reserve: TextProperties,
    pub right_id: TextProperties,
    pub right_photo: RectangleProperties,

    pub referee_name: TextProperties,
    pub referee_nation: TextProperties,

    pub piste: TextProperties,
    pub competition_phase: TextProperties,
    pub competition_type: TextProperties,
    pub poule_tableau_id: TextProperties,

    pub start_time: TextProperties,
    pub local_time: TextProperties,
}

pub struct Layout {
    pub background: RectangleProperties,
    // pub left_nation: TextProperties,
    // pub left_flag: RectangleProperties,
    // pub left_name: TextProperties,
    // pub right_nation: TextProperties,
    // pub right_flag: RectangleProperties,
    // pub right_name: TextProperties,
    pub score_l_l: TextProperties,
    pub score_l_r: TextProperties,
    pub score_r_l: TextProperties,
    pub score_r_r: TextProperties,
    pub epee: TextProperties,
    pub sabre: TextProperties,
    pub fleuret: TextProperties,
    pub auto_score_status: TextProperties,
    pub auto_timer_status: TextProperties,
    pub priority_l_cap: TextProperties,
    pub priority_l_text: TextProperties,
    pub priority_r_cap: TextProperties,
    pub priority_r_text: TextProperties,
    pub caution_l_rect: RectangleProperties,
    pub caution_l_text: TextProperties,
    pub penalty_l_rect: RectangleProperties,
    pub penalty_l_text: TextProperties,
    pub passive_l_bot_rect: RectangleProperties,
    pub passive_l_bot_text: TextProperties,
    pub passive_l_top_rect: RectangleProperties,
    pub passive_l_top_text: TextProperties,
    pub caution_r_rect: RectangleProperties,
    pub caution_r_text: TextProperties,
    pub penalty_r_rect: RectangleProperties,
    pub penalty_r_text: TextProperties,
    pub passive_r_bot_rect: RectangleProperties,
    pub passive_r_bot_text: TextProperties,
    pub passive_r_top_rect: RectangleProperties,
    pub passive_r_top_text: TextProperties,
    pub period: TextProperties,
    pub passive_counter_dec: TextProperties,
    pub passive_counter_sec: TextProperties,
    pub timer_m: TextProperties,
    pub timer_colon: TextProperties,
    pub timer_d: TextProperties,
    pub timer_s: TextProperties,
    pub passive_indicator: RectangleProperties,
    pub left_color_indicator: RectangleProperties,
    pub right_color_indicator: RectangleProperties,
    pub left_white_indicator: RectangleProperties,
    pub right_white_indicator: RectangleProperties,
    pub recording_indicator: RectangleProperties,
    pub timer_text: TextProperties,

    pub cyrano_layout: Option<CyranoLayout>,
}
