// Generated file
use crate::sdl_frontend::colors;
use crate::sdl_frontend::layout_structure::*;

pub const LAYOUT_1920X550: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 550,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: 0,
        y: 41,
        width: 240,
        height: 539,
        font_size: 550,
    },
    score_l_r: TextProperties {
        x: 240,
        y: 41,
        width: 240,
        height: 540,
        font_size: 550,
    },
    score_r_l: TextProperties {
        x: 1440,
        y: -16,
        width: 254,
        height: 440,
        font_size: 550,
    },
    score_r_r: TextProperties {
        x: 1681,
        y: 41,
        width: 240,
        height: 540,
        font_size: 550,
    },
    epee: TextProperties {
        x: 860,
        y: 429,
        width: 200,
        height: 124,
        font_size: 80,
    },
    sabre: TextProperties {
        x: 1060,
        y: 429,
        width: 200,
        height: 124,
        font_size: 80,
    },
    fleuret: TextProperties {
        x: 660,
        y: 429,
        width: 200,
        height: 124,
        font_size: 80,
    },
    disable_inactive_weapon: false,
    auto_score_status: TextProperties {
        x: 491,
        y: 480,
        width: 120,
        height: 99,
        font_size: 24,
    },
    auto_timer_status: TextProperties {
        x: 1318,
        y: 480,
        width: 120,
        height: 99,
        font_size: 24,
    },
    auto_status_only: false,
    priority_l_cap: TextProperties {
        x: 501,
        y: 325,
        width: 55,
        height: 180,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 526,
        y: 430,
        width: 80,
        height: 55,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1329,
        y: 325,
        width: 45,
        height: 180,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1354,
        y: 430,
        width: 80,
        height: 55,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 496,
        y: 285,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 496,
        y: 285,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_l_rect: RectangleProperties {
        x: 496,
        y: 145,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_text: TextProperties {
        x: 496,
        y: 145,
        width: 100,
        height: 55,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1324,
        y: 285,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1324,
        y: 285,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_r_rect: RectangleProperties {
        x: 1324,
        y: 145,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_text: TextProperties {
        x: 1324,
        y: 145,
        width: 100,
        height: 55,
        font_size: 36,
    },
    period: TextProperties {
        x: 604,
        y: 201,
        width: 152,
        height: 212,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 604,
        y: 37,
        width: 76,
        height: 175,
        font_size: 120,
    },
    passive_counter_sec: TextProperties {
        x: 680,
        y: 37,
        width: 76,
        height: 175,
        font_size: 120,
    },
    timer_m: TextProperties {
        x: 765,
        y: 80,
        width: 160,
        height: 365,
        font_size: 320,
    },
    timer_colon: TextProperties {
        x: 925,
        y: 80,
        width: 63,
        height: 365,
        font_size: 330,
    },
    timer_d: TextProperties {
        x: 988,
        y: 80,
        width: 160,
        height: 365,
        font_size: 330,
    },
    timer_s: TextProperties {
        x: 1148,
        y: 80,
        width: 160,
        height: 365,
        font_size: 330,
    },
    passive_indicator: RectangleProperties {
        x: 496,
        y: 10,
        width: 928,
        height: 40,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 27,
        y: 10,
        width: 268,
        height: 40,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1625,
        y: 10,
        width: 282,
        height: 40,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 319,
        y: 10,
        width: 134,
        height: 40,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1467,
        y: 10,
        width: 134,
        height: 40,
        radius: 3,
    },
    timer_text: TextProperties {
        x: 765,
        y: 81,
        width: 543,
        height: 365,
        font_size: 64,
    },

    cyrano_layout: None,
};

pub const LAYOUT_1920X1080: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 1080,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: 0,
        y: 610,
        width: 240,
        height: 470,
        font_size: 550,
    },
    score_l_r: TextProperties {
        x: 240,
        y: 610,
        width: 240,
        height: 470,
        font_size: 550,
    },
    score_r_l: TextProperties {
        x: 1440,
        y: 610,
        width: 240,
        height: 470,
        font_size: 550,
    },
    score_r_r: TextProperties {
        x: 1680,
        y: 610,
        width: 240,
        height: 470,
        font_size: 550,
    },
    epee: TextProperties {
        x: 1046,
        y: 932,
        width: 188,
        height: 74,
        font_size: 56,
    },
    sabre: TextProperties {
        x: 1046,
        y: 932,
        width: 188,
        height: 74,
        font_size: 56,
    },
    fleuret: TextProperties {
        x: 1046,
        y: 932,
        width: 188,
        height: 74,
        font_size: 56,
    },
    disable_inactive_weapon: true,
    auto_score_status: TextProperties {
        x: 576,
        y: 974,
        width: 36,
        height: 44,
        font_size: 36,
    },
    auto_timer_status: TextProperties {
        x: 576,
        y: 1018,
        width: 36,
        height: 44,
        font_size: 36,
    },
    auto_status_only: true,
    priority_l_cap: TextProperties {
        x: 495,
        y: 680,
        width: 100,
        height: 160,
        font_size: 180,
    },
    priority_l_text: TextProperties {
        x: 1920,
        y: 1080,
        width: 80,
        height: 55,
        font_size: 0,
    },
    priority_r_cap: TextProperties {
        x: 1325,
        y: 680,
        width: 100,
        height: 160,
        font_size: 0,
    },
    priority_r_text: TextProperties {
        x: 1920,
        y: 1080,
        width: 80,
        height: 55,
        font_size: 0,
    },
    caution_l_rect: RectangleProperties {
        x: 495,
        y: 615,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 495,
        y: 615,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_l_rect: RectangleProperties {
        x: 495,
        y: 545,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_text: TextProperties {
        x: 495,
        y: 545,
        width: 100,
        height: 55,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1325,
        y: 615,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1325,
        y: 615,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_r_rect: RectangleProperties {
        x: 1325,
        y: 545,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_text: TextProperties {
        x: 1325,
        y: 545,
        width: 100,
        height: 55,
        font_size: 36,
    },
    period: TextProperties {
        x: 625,
        y: 697,
        width: 125,
        height: 166,
        font_size: 180,
    },
    passive_counter_dec: TextProperties {
        x: 625,
        y: 545,
        width: 60,
        height: 108,
        font_size: 120,
    },
    passive_counter_sec: TextProperties {
        x: 685,
        y: 545,
        width: 60,
        height: 108,
        font_size: 120,
    },
    timer_m: TextProperties {
        x: 750,
        y: 632,
        width: 160,
        height: 300,
        font_size: 330,
    },
    timer_colon: TextProperties {
        x: 910,
        y: 632,
        width: 63,
        height: 300,
        font_size: 330,
    },
    timer_d: TextProperties {
        x: 973,
        y: 632,
        width: 160,
        height: 300,
        font_size: 330,
    },
    timer_s: TextProperties {
        x: 1134,
        y: 632,
        width: 160,
        height: 300,
        font_size: 330,
    },
    passive_indicator: RectangleProperties {
        x: 625,
        y: 510,
        width: 670,
        height: 15,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 5,
        y: 560,
        width: 320,
        height: 50,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1595,
        y: 560,
        width: 320,
        height: 50,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 336,
        y: 560,
        width: 135,
        height: 50,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1449,
        y: 560,
        width: 135,
        height: 50,
        radius: 3,
    },
    timer_text: TextProperties {
        x: 750,
        y: 632,
        width: 543,
        height: 300,
        font_size: 64,
    },

    cyrano_layout: Some(CyranoLayout {
        left_name: TextProperties {
            x: 0,
            y: 0,
            width: 700,
            height: 170,
            font_size: 140,
        },
        left_nation: TextProperties {
            x: 290,
            y: 170,
            width: 120,
            height: 90,
            font_size: 72,
        },
        left_flag: RectangleProperties {
            x: 290,
            y: 260,
            width: 120,
            height: 120,
            radius: 0,
        },
        left_score: TextProperties {
            x: 290,
            y: 380,
            width: 120,
            height: 160,
            font_size: 180,
        },
        left_status: TextProperties {
            x: 430,
            y: 170,
            width: 40,
            height: 90,
            font_size: 72,
        },
        left_video: TextProperties {
            x: 430,
            y: 260,
            width: 40,
            height: 90,
            font_size: 72,
        },
        left_medical: TextProperties {
            x: 430,
            y: 350,
            width: 40,
            height: 90,
            font_size: 72,
        },
        left_reserve: TextProperties {
            x: 430,
            y: 440,
            width: 40,
            height: 90,
            font_size: 72,
        },
        left_id: TextProperties {
            x: 5,
            y: 560,
            width: 320,
            height: 50,
            font_size: 36,
        },
        left_photo: RectangleProperties {
            x: 0,
            y: 180,
            width: 270,
            height: 360,
            radius: 0,
        },

        right_name: TextProperties {
            x: 1220,
            y: 0,
            width: 700,
            height: 170,
            font_size: 140,
        },
        right_nation: TextProperties {
            x: 1510,
            y: 170,
            width: 120,
            height: 90,
            font_size: 72,
        },
        right_flag: RectangleProperties {
            x: 1510,
            y: 260,
            width: 120,
            height: 120,
            radius: 0,
        },
        right_score: TextProperties {
            x: 1510,
            y: 380,
            width: 120,
            height: 160,
            font_size: 180,
        },
        right_status: TextProperties {
            x: 1450,
            y: 170,
            width: 40,
            height: 90,
            font_size: 72,
        },
        right_video: TextProperties {
            x: 1450,
            y: 260,
            width: 40,
            height: 90,
            font_size: 72,
        },
        right_medical: TextProperties {
            x: 1450,
            y: 350,
            width: 40,
            height: 90,
            font_size: 72,
        },
        right_reserve: TextProperties {
            x: 1450,
            y: 440,
            width: 40,
            height: 90,
            font_size: 72,
        },
        right_id: TextProperties {
            x: 1595,
            y: 560,
            width: 320,
            height: 50,
            font_size: 36,
        },
        right_photo: RectangleProperties {
            x: 1650,
            y: 180,
            width: 270,
            height: 360,
            radius: 0,
        },

        referee_name: TextProperties {
            x: 865,
            y: 547,
            width: 320,
            height: 74,
            font_size: 56,
        },
        referee_nation: TextProperties {
            x: 1185,
            y: 547,
            width: 110,
            height: 74,
            font_size: 56,
        },
        piste: TextProperties {
            x: 880,
            y: 0,
            width: 340,
            height: 90,
            font_size: 48,
        },
        competition_phase: TextProperties {
            x: 880,
            y: 270,
            width: 340,
            height: 90,
            font_size: 72,
        },
        competition_type: TextProperties {
            x: 880,
            y: 90,
            width: 340,
            height: 90,
            font_size: 72,
        },
        poule_tableau_id: TextProperties {
            x: 880,
            y: 180,
            width: 340,
            height: 90,
            font_size: 72,
        },
        start_time: TextProperties {
            x: 805,
            y: 332,
            width: 300,
            height: 100,
            font_size: 48,
        },
        local_time: TextProperties {
            x: 805,
            y: 416,
            width: 300,
            height: 100,
            font_size: 48,
        },

        state: TextProperties {
            x: 1046,
            y: 1006,
            width: 188,
            height: 74,
            font_size: 56,
        },
        status: TextProperties {
            x: 1285,
            y: 928,
            width: 140,
            height: 108,
            font_size: 100,
        },
    }),
};

pub const LAYOUT_1920X360: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 360,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: 0,
        y: 48,
        width: 180,
        height: 312,
        font_size: 370,
    },
    score_l_r: TextProperties {
        x: 180,
        y: 48,
        width: 180,
        height: 311,
        font_size: 370,
    },
    score_r_l: TextProperties {
        x: 1560,
        y: 47,
        width: 180,
        height: 312,
        font_size: 370,
    },
    score_r_r: TextProperties {
        x: 1740,
        y: 48,
        width: 180,
        height: 312,
        font_size: 370,
    },
    epee: TextProperties {
        x: 927,
        y: 280,
        width: 160,
        height: 80,
        font_size: 60,
    },
    sabre: TextProperties {
        x: 1087,
        y: 280,
        width: 160,
        height: 80,
        font_size: 60,
    },
    fleuret: TextProperties {
        x: 767,
        y: 279,
        width: 160,
        height: 80,
        font_size: 60,
    },
    disable_inactive_weapon: false,
    auto_score_status: TextProperties {
        x: 360,
        y: 280,
        width: 120,
        height: 80,
        font_size: 32,
    },
    auto_timer_status: TextProperties {
        x: 1440,
        y: 280,
        width: 120,
        height: 80,
        font_size: 32,
    },
    auto_status_only: false,
    priority_l_cap: TextProperties {
        x: 365,
        y: 104,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 390,
        y: 188,
        width: 80,
        height: 44,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1445,
        y: 104,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1470,
        y: 188,
        width: 80,
        height: 44,
        font_size: 36,
    },
    passive_l_rect: RectangleProperties {
        x: 492,
        y: 240,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_text: TextProperties {
        x: 492,
        y: 240,
        width: 100,
        height: 44,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 492,
        y: 128,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 492,
        y: 128,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_rect: RectangleProperties {
        x: 1328,
        y: 240,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_text: TextProperties {
        x: 1328,
        y: 240,
        width: 100,
        height: 44,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1328,
        y: 128,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1328,
        y: 128,
        width: 100,
        height: 44,
        font_size: 36,
    },
    period: TextProperties {
        x: 604,
        y: 190,
        width: 152,
        height: 170,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 604,
        y: 48,
        width: 76,
        height: 140,
        font_size: 160,
    },
    passive_counter_sec: TextProperties {
        x: 680,
        y: 48,
        width: 76,
        height: 140,
        font_size: 160,
    },
    timer_m: TextProperties {
        x: 784,
        y: 24,
        width: 140,
        height: 270,
        font_size: 280,
    },
    timer_colon: TextProperties {
        x: 925,
        y: 24,
        width: 50,
        height: 270,
        font_size: 280,
    },
    timer_d: TextProperties {
        x: 975,
        y: 24,
        width: 140,
        height: 270,
        font_size: 280,
    },
    timer_s: TextProperties {
        x: 1115,
        y: 24,
        width: 140,
        height: 270,
        font_size: 280,
    },
    passive_indicator: RectangleProperties {
        x: 491,
        y: 8,
        width: 936,
        height: 32,
        radius: 0,
    },
    left_color_indicator: RectangleProperties {
        x: 8,
        y: 8,
        width: 224,
        height: 32,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1688,
        y: 8,
        width: 224,
        height: 32,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 240,
        y: 8,
        width: 120,
        height: 32,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1568,
        y: 8,
        width: 112,
        height: 32,
        radius: 3,
    },
    timer_text: TextProperties {
        x: 785,
        y: 24,
        width: 462,
        height: 270,
        font_size: 64,
    },

    cyrano_layout: None,
};

pub const LAYOUT_1920X480: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 480,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: 0,
        y: 48,
        width: 240,
        height: 431,
        font_size: 500,
    },
    score_l_r: TextProperties {
        x: 240,
        y: 48,
        width: 240,
        height: 432,
        font_size: 500,
    },
    score_r_l: TextProperties {
        x: 1440,
        y: 47,
        width: 240,
        height: 432,
        font_size: 500,
    },
    score_r_r: TextProperties {
        x: 1680,
        y: 47,
        width: 240,
        height: 432,
        font_size: 500,
    },
    epee: TextProperties {
        x: 860,
        y: 380,
        width: 200,
        height: 100,
        font_size: 80,
    },
    sabre: TextProperties {
        x: 1060,
        y: 380,
        width: 200,
        height: 100,
        font_size: 80,
    },
    fleuret: TextProperties {
        x: 660,
        y: 379,
        width: 200,
        height: 100,
        font_size: 80,
    },
    disable_inactive_weapon: false,
    auto_score_status: TextProperties {
        x: 486,
        y: 400,
        width: 120,
        height: 80,
        font_size: 32,
    },
    auto_timer_status: TextProperties {
        x: 1314,
        y: 400,
        width: 120,
        height: 80,
        font_size: 32,
    },
    auto_status_only: false,
    priority_l_cap: TextProperties {
        x: 501,
        y: 276,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 526,
        y: 360,
        width: 80,
        height: 44,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1329,
        y: 276,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1354,
        y: 360,
        width: 80,
        height: 44,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 496,
        y: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 496,
        y: 244,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_l_rect: RectangleProperties {
        x: 496,
        y: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_text: TextProperties {
        x: 496,
        y: 132,
        width: 100,
        height: 44,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1324,
        y: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1324,
        y: 244,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_rect: RectangleProperties {
        x: 1324,
        y: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_text: TextProperties {
        x: 1324,
        y: 132,
        width: 100,
        height: 44,
        font_size: 36,
    },
    period: TextProperties {
        x: 604,
        y: 206,
        width: 152,
        height: 170,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 604,
        y: 69,
        width: 76,
        height: 140,
        font_size: 160,
    },
    passive_counter_sec: TextProperties {
        x: 680,
        y: 69,
        width: 76,
        height: 140,
        font_size: 160,
    },
    timer_m: TextProperties {
        x: 764,
        y: 80,
        width: 160,
        height: 292,
        font_size: 320,
    },
    timer_colon: TextProperties {
        x: 925,
        y: 80,
        width: 63,
        height: 292,
        font_size: 330,
    },
    timer_d: TextProperties {
        x: 988,
        y: 80,
        width: 160,
        height: 292,
        font_size: 330,
    },
    timer_s: TextProperties {
        x: 1148,
        y: 80,
        width: 160,
        height: 292,
        font_size: 330,
    },
    passive_indicator: RectangleProperties {
        x: 496,
        y: 24,
        width: 928,
        height: 32,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 27,
        y: 24,
        width: 268,
        height: 32,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1625,
        y: 24,
        width: 268,
        height: 32,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 319,
        y: 24,
        width: 134,
        height: 32,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1467,
        y: 24,
        width: 134,
        height: 32,
        radius: 3,
    },
    timer_text: TextProperties {
        x: 764,
        y: 80,
        width: 544,
        height: 292,
        font_size: 64,
    },

    cyrano_layout: None,
};

pub fn get_static_layout_1920x1080() -> Vec<(TextProperties, sdl2::pixels::Color, String)> {
    vec![
        (
            TextProperties {
                x: 527,
                y: 930,
                width: 56,
                height: 44,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Auto".into(),
        ),
        (
            TextProperties {
                x: 497,
                y: 974,
                width: 74,
                height: 44,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Score".into(),
        ),
        (
            TextProperties {
                x: 497,
                y: 1018,
                width: 72,
                height: 44,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Timer".into(),
        ),
        (
            TextProperties {
                x: 806,
                y: 932,
                width: 240,
                height: 74,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Weapon select".into(),
        ),
        (
            TextProperties {
                x: 806,
                y: 1006,
                width: 240,
                height: 74,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Apparate state".into(),
        ),
        (
            TextProperties {
                x: 1285,
                y: 1036,
                width: 140,
                height: 44,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Activity".into(),
        ),
        (
            TextProperties {
                x: 495,
                y: 840,
                width: 140,
                height: 44,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Priority".into(),
        ),
        (
            TextProperties {
                x: 1325,
                y: 840,
                width: 140,
                height: 44,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Priority".into(),
        ),
        (
            TextProperties {
                x: 625,
                y: 863,
                width: 125,
                height: 44,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Round".into(),
        ),
        (
            TextProperties {
                x: 625,
                y: 653,
                width: 120,
                height: 44,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Passivity".into(),
        ),
        (
            TextProperties {
                x: 745,
                y: 577,
                width: 120,
                height: 44,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Arbitre".into(),
        ),
        (
            TextProperties {
                x: 470,
                y: 199,
                width: 80,
                height: 61,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Status".into(),
        ),
        (
            TextProperties {
                x: 470,
                y: 289,
                width: 67,
                height: 61,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Video".into(),
        ),
        (
            TextProperties {
                x: 470,
                y: 379,
                width: 92,
                height: 61,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Medical".into(),
        ),
        (
            TextProperties {
                x: 470,
                y: 469,
                width: 102,
                height: 61,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Reserve".into(),
        ),
        (
            TextProperties {
                x: 1370,
                y: 199,
                width: 80,
                height: 61,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Status".into(),
        ),
        (
            TextProperties {
                x: 1383,
                y: 289,
                width: 67,
                height: 61,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Video".into(),
        ),
        (
            TextProperties {
                x: 1358,
                y: 379,
                width: 92,
                height: 61,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Medical".into(),
        ),
        (
            TextProperties {
                x: 1348,
                y: 469,
                width: 102,
                height: 61,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Reserve".into(),
        ),
        (
            TextProperties {
                x: 800,
                y: 46,
                width: 80,
                height: 44,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Piste".into(),
        ),
        (
            TextProperties {
                x: 669,
                y: 136,
                width: 211,
                height: 44,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Competition Type".into(),
        ),
        (
            TextProperties {
                x: 666,
                y: 226,
                width: 214,
                height: 44,
                font_size: 36,
            },
            colors::STATIC_TEXT,
            "Tableau Identifier".into(),
        ),
    ]
}
