// Generated file
use crate::sdl_frontend::layout_structure::*;

pub const LAYOUT_1920X550: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 550,
        radius: 0,
    },
    left_nation: TextProperties {
        x: 26,
        y: -294,
        width: 84,
        height: 71,
        font_size: 60,
    },
    left_flag: RectangleProperties {
        x: 118,
        y: -281,
        width: 72,
        height: 47,
        radius: 0,
    },
    left_name: TextProperties {
        x: 0,
        y: -222,
        width: 480,
        height: 108,
        font_size: 90,
    },
    right_nation: TextProperties {
        x: 1466,
        y: -294,
        width: 84,
        height: 71,
        font_size: 60,
    },
    right_flag: RectangleProperties {
        x: 1558,
        y: -281,
        width: 72,
        height: 47,
        radius: 0,
    },
    right_name: TextProperties {
        x: 1440,
        y: -222,
        width: 480,
        height: 108,
        font_size: 90,
    },
    score_l_l: TextProperties {
        x: 0,
        y: 41,
        width: 240,
        height: 539,
        font_size: 550,
    },
    score_l_r: TextProperties {
        x: 240,
        y: 41,
        width: 240,
        height: 540,
        font_size: 550,
    },
    score_r_l: TextProperties {
        x: 1440,
        y: -16,
        width: 254,
        height: 440,
        font_size: 550,
    },
    score_r_r: TextProperties {
        x: 1681,
        y: 41,
        width: 240,
        height: 540,
        font_size: 550,
    },
    epee: TextProperties {
        x: 860,
        y: 429,
        width: 200,
        height: 124,
        font_size: 80,
    },
    sabre: TextProperties {
        x: 1060,
        y: 429,
        width: 200,
        height: 124,
        font_size: 80,
    },
    fleuret: TextProperties {
        x: 660,
        y: 429,
        width: 200,
        height: 124,
        font_size: 80,
    },
    auto_score_status: TextProperties {
        x: 491,
        y: 480,
        width: 120,
        height: 99,
        font_size: 24,
    },
    auto_timer_status: TextProperties {
        x: 1318,
        y: 480,
        width: 120,
        height: 99,
        font_size: 24,
    },
    priority_l_cap: TextProperties {
        x: 501,
        y: 325,
        width: 55,
        height: 180,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 526,
        y: 430,
        width: 80,
        height: 55,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1329,
        y: 325,
        width: 45,
        height: 180,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1354,
        y: 430,
        width: 80,
        height: 55,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 496,
        y: 285,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 496,
        y: 285,
        width: 100,
        height: 55,
        font_size: 36,
    },
    penalty_l_rect: RectangleProperties {
        x: 496,
        y: 220,
        width: 100,
        height: 55,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 496,
        y: 220,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 496,
        y: 145,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 496,
        y: 145,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_l_top_rect: RectangleProperties {
        x: 496,
        y: 80,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 496,
        y: 80,
        width: 100,
        height: 55,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1324,
        y: 285,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1324,
        y: 285,
        width: 100,
        height: 55,
        font_size: 36,
    },
    penalty_r_rect: RectangleProperties {
        x: 1324,
        y: 220,
        width: 100,
        height: 55,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1324,
        y: 220,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1324,
        y: 145,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1324,
        y: 145,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1324,
        y: 80,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1324,
        y: 80,
        width: 100,
        height: 55,
        font_size: 36,
    },
    period: TextProperties {
        x: 604,
        y: 201,
        width: 152,
        height: 212,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 604,
        y: 37,
        width: 76,
        height: 175,
        font_size: 120,
    },
    passive_counter_sec: TextProperties {
        x: 680,
        y: 37,
        width: 76,
        height: 175,
        font_size: 120,
    },
    timer_m: TextProperties {
        x: 765,
        y: 80,
        width: 160,
        height: 365,
        font_size: 320,
    },
    timer_colon: TextProperties {
        x: 925,
        y: 80,
        width: 63,
        height: 365,
        font_size: 330,
    },
    timer_d: TextProperties {
        x: 988,
        y: 80,
        width: 160,
        height: 365,
        font_size: 330,
    },
    timer_s: TextProperties {
        x: 1148,
        y: 80,
        width: 160,
        height: 365,
        font_size: 330,
    },
    passive_indicator: RectangleProperties {
        x: 496,
        y: 10,
        width: 928,
        height: 40,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 27,
        y: 10,
        width: 268,
        height: 40,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1625,
        y: 10,
        width: 282,
        height: 40,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 319,
        y: 10,
        width: 134,
        height: 40,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1467,
        y: 10,
        width: 134,
        height: 40,
        radius: 3,
    },
    recording_indicator: RectangleProperties {
        x: 1256,
        y: 80,
        width: 32,
        height: 32,
        radius: 16,
    },
    timer_text: TextProperties {
        x: 765,
        y: 81,
        width: 543,
        height: 365,
        font_size: 64,
    },
};

pub const LAYOUT_1920X1080: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 1080,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: 0,
        y: 540,
        width: 240,
        height: 539,
        font_size: 550,
    },
    score_l_r: TextProperties {
        x: 239,
        y: 540,
        width: 240,
        height: 540,
        font_size: 550,
    },
    score_r_l: TextProperties {
        x: 1440,
        y: 540,
        width: 240,
        height: 540,
        font_size: 550,
    },
    score_r_r: TextProperties {
        x: 1680,
        y: 540,
        width: 240,
        height: 540,
        font_size: 550,
    },
    epee: TextProperties {
        x: 859,
        y: 928,
        width: 200,
        height: 125,
        font_size: 80,
    },
    sabre: TextProperties {
        x: 1059,
        y: 928,
        width: 200,
        height: 125,
        font_size: 80,
    },
    fleuret: TextProperties {
        x: 659,
        y: 928,
        width: 200,
        height: 125,
        font_size: 80,
    },
    auto_score_status: TextProperties {
        x: 490,
        y: 979,
        width: 120,
        height: 100,
        font_size: 24,
    },
    auto_timer_status: TextProperties {
        x: 1317,
        y: 979,
        width: 120,
        height: 100,
        font_size: 24,
    },
    priority_l_cap: TextProperties {
        x: 500,
        y: 824,
        width: 55,
        height: 180,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 525,
        y: 929,
        width: 80,
        height: 55,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1328,
        y: 824,
        width: 45,
        height: 180,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1353,
        y: 929,
        width: 80,
        height: 55,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 495,
        y: 784,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 495,
        y: 784,
        width: 100,
        height: 55,
        font_size: 36,
    },
    penalty_l_rect: RectangleProperties {
        x: 495,
        y: 719,
        width: 100,
        height: 55,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 495,
        y: 719,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 495,
        y: 644,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 495,
        y: 644,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_l_top_rect: RectangleProperties {
        x: 495,
        y: 579,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 495,
        y: 579,
        width: 100,
        height: 55,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1323,
        y: 784,
        width: 100,
        height: 55,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1323,
        y: 784,
        width: 100,
        height: 55,
        font_size: 36,
    },
    penalty_r_rect: RectangleProperties {
        x: 1323,
        y: 719,
        width: 100,
        height: 55,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1323,
        y: 719,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1323,
        y: 644,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1323,
        y: 644,
        width: 100,
        height: 55,
        font_size: 36,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1323,
        y: 579,
        width: 100,
        height: 55,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1323,
        y: 579,
        width: 100,
        height: 55,
        font_size: 36,
    },
    period: TextProperties {
        x: 603,
        y: 700,
        width: 152,
        height: 213,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 603,
        y: 537,
        width: 76,
        height: 175,
        font_size: 120,
    },
    passive_counter_sec: TextProperties {
        x: 679,
        y: 537,
        width: 76,
        height: 175,
        font_size: 120,
    },
    timer_m: TextProperties {
        x: 764,
        y: 579,
        width: 160,
        height: 365,
        font_size: 320,
    },
    timer_colon: TextProperties {
        x: 924,
        y: 579,
        width: 63,
        height: 365,
        font_size: 330,
    },
    timer_d: TextProperties {
        x: 987,
        y: 579,
        width: 160,
        height: 365,
        font_size: 330,
    },
    timer_s: TextProperties {
        x: 1147,
        y: 579,
        width: 160,
        height: 365,
        font_size: 330,
    },
    passive_indicator: RectangleProperties {
        x: 495,
        y: 509,
        width: 928,
        height: 40,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 26,
        y: 509,
        width: 268,
        height: 40,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1624,
        y: 509,
        width: 282,
        height: 40,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 318,
        y: 509,
        width: 134,
        height: 40,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1466,
        y: 509,
        width: 134,
        height: 40,
        radius: 3,
    },
    recording_indicator: RectangleProperties {
        x: 1256,
        y: 580,
        width: 32,
        height: 32,
        radius: 16,
    },
    left_nation: TextProperties {
        x: 26,
        y: 26,
        width: 84,
        height: 72,
        font_size: 60,
    },
    left_flag: RectangleProperties {
        x: 118,
        y: 39,
        width: 72,
        height: 48,
        radius: 0,
    },
    left_name: TextProperties {
        x: 0,
        y: 98,
        width: 480,
        height: 108,
        font_size: 90,
    },
    right_nation: TextProperties {
        x: 1466,
        y: 26,
        width: 84,
        height: 72,
        font_size: 60,
    },
    right_flag: RectangleProperties {
        x: 1558,
        y: 39,
        width: 72,
        height: 48,
        radius: 0,
    },
    right_name: TextProperties {
        x: 1440,
        y: 98,
        width: 480,
        height: 108,
        font_size: 90,
    },
    timer_text: TextProperties {
        x: 765,
        y: 579,
        width: 543,
        height: 365,
        font_size: 64,
    },
};

pub const LAYOUT_1920X360: Layout = Layout {
    left_nation: TextProperties {
        x: 26,
        y: -294,
        width: 84,
        height: 72,
        font_size: 60,
    },
    left_flag: RectangleProperties {
        x: 118,
        y: -281,
        width: 72,
        height: 48,
        radius: 0,
    },
    left_name: TextProperties {
        x: 0,
        y: -222,
        width: 480,
        height: 108,
        font_size: 90,
    },
    right_nation: TextProperties {
        x: 1466,
        y: -294,
        width: 84,
        height: 72,
        font_size: 60,
    },
    right_flag: RectangleProperties {
        x: 1558,
        y: -281,
        width: 72,
        height: 48,
        radius: 0,
    },
    right_name: TextProperties {
        x: 1440,
        y: -222,
        width: 480,
        height: 108,
        font_size: 90,
    },
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 360,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: 0,
        y: 48,
        width: 180,
        height: 312,
        font_size: 370,
    },
    score_l_r: TextProperties {
        x: 180,
        y: 48,
        width: 180,
        height: 311,
        font_size: 370,
    },
    score_r_l: TextProperties {
        x: 1560,
        y: 47,
        width: 180,
        height: 312,
        font_size: 370,
    },
    score_r_r: TextProperties {
        x: 1740,
        y: 48,
        width: 180,
        height: 312,
        font_size: 370,
    },
    epee: TextProperties {
        x: 927,
        y: 280,
        width: 160,
        height: 80,
        font_size: 60,
    },
    sabre: TextProperties {
        x: 1087,
        y: 280,
        width: 160,
        height: 80,
        font_size: 60,
    },
    fleuret: TextProperties {
        x: 767,
        y: 279,
        width: 160,
        height: 80,
        font_size: 60,
    },
    auto_score_status: TextProperties {
        x: 360,
        y: 280,
        width: 120,
        height: 80,
        font_size: 32,
    },
    auto_timer_status: TextProperties {
        x: 1440,
        y: 280,
        width: 120,
        height: 80,
        font_size: 32,
    },
    priority_l_cap: TextProperties {
        x: 365,
        y: 104,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 390,
        y: 188,
        width: 80,
        height: 44,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1445,
        y: 104,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1470,
        y: 188,
        width: 80,
        height: 44,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 492,
        y: 240,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 492,
        y: 240,
        width: 100,
        height: 44,
        font_size: 36,
    },
    penalty_l_rect: RectangleProperties {
        x: 492,
        y: 188,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 492,
        y: 188,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 492,
        y: 128,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 492,
        y: 128,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_l_top_rect: RectangleProperties {
        x: 492,
        y: 76,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 492,
        y: 76,
        width: 100,
        height: 44,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1328,
        y: 240,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1328,
        y: 240,
        width: 100,
        height: 44,
        font_size: 36,
    },
    penalty_r_rect: RectangleProperties {
        x: 1328,
        y: 188,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1328,
        y: 188,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1328,
        y: 128,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1328,
        y: 128,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1328,
        y: 76,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1328,
        y: 76,
        width: 100,
        height: 44,
        font_size: 36,
    },
    period: TextProperties {
        x: 604,
        y: 190,
        width: 152,
        height: 170,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 604,
        y: 48,
        width: 76,
        height: 140,
        font_size: 160,
    },
    passive_counter_sec: TextProperties {
        x: 680,
        y: 48,
        width: 76,
        height: 140,
        font_size: 160,
    },
    timer_m: TextProperties {
        x: 784,
        y: 24,
        width: 140,
        height: 270,
        font_size: 280,
    },
    timer_colon: TextProperties {
        x: 925,
        y: 24,
        width: 50,
        height: 270,
        font_size: 280,
    },
    timer_d: TextProperties {
        x: 975,
        y: 24,
        width: 140,
        height: 270,
        font_size: 280,
    },
    timer_s: TextProperties {
        x: 1115,
        y: 24,
        width: 140,
        height: 270,
        font_size: 280,
    },
    passive_indicator: RectangleProperties {
        x: 491,
        y: 8,
        width: 936,
        height: 32,
        radius: 0,
    },
    left_color_indicator: RectangleProperties {
        x: 8,
        y: 8,
        width: 224,
        height: 32,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1688,
        y: 8,
        width: 224,
        height: 32,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 240,
        y: 8,
        width: 120,
        height: 32,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1568,
        y: 8,
        width: 112,
        height: 32,
        radius: 3,
    },
    recording_indicator: RectangleProperties {
        x: 1254,
        y: 56,
        width: 32,
        height: 32,
        radius: 16,
    },
    timer_text: TextProperties {
        x: 785,
        y: 24,
        width: 462,
        height: 270,
        font_size: 64,
    },
};

pub const LAYOUT_1920X480: Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 480,
        radius: 0,
    },
    left_nation: TextProperties {
        x: 26,
        y: -294,
        width: 84,
        height: 72,
        font_size: 60,
    },
    left_flag: RectangleProperties {
        x: 118,
        y: -281,
        width: 72,
        height: 48,
        radius: 0,
    },
    left_name: TextProperties {
        x: 0,
        y: -222,
        width: 480,
        height: 108,
        font_size: 90,
    },
    right_nation: TextProperties {
        x: 1466,
        y: -294,
        width: 84,
        height: 72,
        font_size: 60,
    },
    right_flag: RectangleProperties {
        x: 1558,
        y: -281,
        width: 72,
        height: 48,
        radius: 0,
    },
    right_name: TextProperties {
        x: 1440,
        y: -222,
        width: 480,
        height: 108,
        font_size: 90,
    },
    score_l_l: TextProperties {
        x: 0,
        y: 48,
        width: 240,
        height: 431,
        font_size: 500,
    },
    score_l_r: TextProperties {
        x: 240,
        y: 48,
        width: 240,
        height: 432,
        font_size: 500,
    },
    score_r_l: TextProperties {
        x: 1440,
        y: 47,
        width: 240,
        height: 432,
        font_size: 500,
    },
    score_r_r: TextProperties {
        x: 1680,
        y: 47,
        width: 240,
        height: 432,
        font_size: 500,
    },
    epee: TextProperties {
        x: 860,
        y: 380,
        width: 200,
        height: 100,
        font_size: 80,
    },
    sabre: TextProperties {
        x: 1060,
        y: 380,
        width: 200,
        height: 100,
        font_size: 80,
    },
    fleuret: TextProperties {
        x: 660,
        y: 379,
        width: 200,
        height: 100,
        font_size: 80,
    },
    auto_score_status: TextProperties {
        x: 486,
        y: 400,
        width: 120,
        height: 80,
        font_size: 32,
    },
    auto_timer_status: TextProperties {
        x: 1314,
        y: 400,
        width: 120,
        height: 80,
        font_size: 32,
    },
    priority_l_cap: TextProperties {
        x: 501,
        y: 276,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 526,
        y: 360,
        width: 80,
        height: 44,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1329,
        y: 276,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1354,
        y: 360,
        width: 80,
        height: 44,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 496,
        y: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 496,
        y: 244,
        width: 100,
        height: 44,
        font_size: 36,
    },
    penalty_l_rect: RectangleProperties {
        x: 496,
        y: 192,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 496,
        y: 192,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 496,
        y: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 496,
        y: 132,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_l_top_rect: RectangleProperties {
        x: 496,
        y: 80,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 496,
        y: 80,
        width: 100,
        height: 44,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1324,
        y: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1324,
        y: 244,
        width: 100,
        height: 44,
        font_size: 36,
    },
    penalty_r_rect: RectangleProperties {
        x: 1324,
        y: 192,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1324,
        y: 192,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1324,
        y: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1324,
        y: 132,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1324,
        y: 80,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1324,
        y: 80,
        width: 100,
        height: 44,
        font_size: 36,
    },
    period: TextProperties {
        x: 604,
        y: 206,
        width: 152,
        height: 170,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 604,
        y: 69,
        width: 76,
        height: 140,
        font_size: 160,
    },
    passive_counter_sec: TextProperties {
        x: 680,
        y: 69,
        width: 76,
        height: 140,
        font_size: 160,
    },
    timer_m: TextProperties {
        x: 764,
        y: 80,
        width: 160,
        height: 292,
        font_size: 320,
    },
    timer_colon: TextProperties {
        x: 925,
        y: 80,
        width: 63,
        height: 292,
        font_size: 330,
    },
    timer_d: TextProperties {
        x: 988,
        y: 80,
        width: 160,
        height: 292,
        font_size: 330,
    },
    timer_s: TextProperties {
        x: 1148,
        y: 80,
        width: 160,
        height: 292,
        font_size: 330,
    },
    passive_indicator: RectangleProperties {
        x: 496,
        y: 24,
        width: 928,
        height: 32,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 27,
        y: 24,
        width: 268,
        height: 32,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1625,
        y: 24,
        width: 268,
        height: 32,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 319,
        y: 24,
        width: 134,
        height: 32,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1467,
        y: 24,
        width: 134,
        height: 32,
        radius: 3,
    },
    recording_indicator: RectangleProperties {
        x: 1258,
        y: 64,
        width: 32,
        height: 32,
        radius: 16,
    },
    timer_text: TextProperties {
        x: 764,
        y: 80,
        width: 544,
        height: 292,
        font_size: 64,
    },
};
